---
name: "kubectl-action"
description: "Lets you run arbitrary kubectl commands."
inputs:
  debug:
    description: "Adds action debug messages. Might contain sensitive data."
    required: false
  config:
    description: "Kubeconfig yaml contents. Can be base64 encoded or just yaml."
    required: false
  eks_cluster:
    description: "Name of the EKS cluster to interact with. Will use aws eks update-kubeconfig."
    required: false
  eks_role_arn:
    description: "The AWS IAM role to use when authenticating with EKS."
    required: false
  context:
    description: "Context to use if there are multiple."
    required: false
  namespace:
    description: "Namespace to use."
    required: false
  run:
    description: "Commands to run."
    required: false
runs:
  using: "docker"
  image: "Dockerfile"
