name: Build, scan, and publish the image

on:
  push:
    branches:
      - main
    tags:
      - v*

jobs:
  build:
    name: Build docker image
    runs-on: ubuntu-22.04
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Prepare docker buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to ghcr.io
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u "${{ github.actor }}" --password-stdin
      - name: Build Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          cache-from: type=gha
          cache-to: type=gha,mode=max
          tags: ghcr.io/ironhalik/kubectl-action-base:${{ github.sha }}

  test-shellcheck:
    name: Run shellcheck
    runs-on: ubuntu-22.04
    permissions:
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: ShellCheck
        uses: ludeeus/action-shellcheck@1.1.0
        with:
          ignore: Dockerfile test/lib/
          severity: warning

  test-trivy:
    name: Run Trivy
    runs-on: ubuntu-22.04
    needs:
      - build
    permissions:
      contents: read
      packages: read
    steps:
      - name: Login to ghcr.io
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u "${{ github.actor }}" --password-stdin
      - name: Pull current image
        run: docker pull ghcr.io/ironhalik/kubectl-action-base:${{ github.sha }}
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@0.8.0
        with:
          image-ref: ghcr.io/ironhalik/kubectl-action-base:${{ github.sha }}
          exit-code: "1"
          ignore-unfixed: true
          vuln-type: "os,library"
          severity: "HIGH,CRITICAL"
          skip-dirs: /usr/local/bin/
          security-checks: "vuln"
          hide-progress: true

  publish-tags:
    name: Publish tagged image
    if: startsWith(github.ref, 'refs/tags/v')
    needs:
      - test-shellcheck
      - test-trivy
    runs-on: ubuntu-22.04
    permissions:
      contents: read
      packages: write
    steps:
      - name: Export extra envs
        uses: FranzDiebold/github-env-vars-action@v2
      - name: Login to ghcr.io
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u "${{ github.actor }}" --password-stdin
      - name: Pull current image
        run: docker pull ghcr.io/ironhalik/kubectl-action-base:${{ github.sha }}
      - name: Tag and push images
        run: |
          docker tag ghcr.io/ironhalik/kubectl-action-base:${{ github.sha }} ghcr.io/ironhalik/kubectl-action-base:${{ env.CI_REF_NAME }}
          docker tag ghcr.io/ironhalik/kubectl-action-base:${{ github.sha }} ghcr.io/ironhalik/kubectl-action-base:${{ env.CI_SHA_SHORT }}
          docker push ghcr.io/ironhalik/kubectl-action-base:${{ env.CI_REF_NAME }}
          docker push ghcr.io/ironhalik/kubectl-action-base:${{ env.CI_SHA_SHORT }}
