name: Build, scan, and publish the image

on:
  push:
    tags:
      - v*

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-test-push:
    name: Build
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: FranzDiebold/github-env-vars-action@v2
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: ShellCheck
        uses: ludeeus/action-shellcheck@1.1.0
        with:
          ignore: Dockerfile
      - name: Build Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          load: true
          tags: ghcr.io/ironhalik/kubectl-action-base:${{ env.CI_REF_NAME }},ghcr.io/ironhalik/kubectl-action-base:${{ env.CI_SHA_SHORT }}
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@0.7.1
        with:
          image-ref: ghcr.io/ironhalik/kubectl-action-base:${{ env.CI_SHA_SHORT }}
          exit-code: "1"
          ignore-unfixed: true
          vuln-type: "os,library"
          severity: "CRITICAL"
      - name: Log in to ghcr.io
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: ghcr.io/ironhalik/kubectl-action-base:${{ env.CI_REF_NAME }},ghcr.io/ironhalik/kubectl-action-base:${{ env.CI_SHA_SHORT }}
