name: Build, scan, and publish the image

on:
  push:
    branches:
      - main
    tags:
      - v*
  workflow_dispatch:

env:
  LOCAL_IMAGE: ghcr.io/ironhalik/kubectl-action:${{ github.sha }}

jobs:
  build:
    name: Build Docker image
    runs-on: ubuntu-22.04
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Prepare docker buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to ghcr.io
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u "${{ github.actor }}" --password-stdin
      - name: Build Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          cache-from: type=gha
          cache-to: type=gha,mode=max
          tags: ${{ env.LOCAL_IMAGE }}

  test-shellcheck:
    name: Run Shellcheck
    runs-on: ubuntu-22.04
    permissions:
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: ShellCheck
        uses: ludeeus/action-shellcheck@2
        with:
          ignore_paths: >-
            Dockerfile
            test/lib/

  test-trivy:
    name: Run Trivy
    runs-on: ubuntu-22.04
    needs:
      - build
    permissions:
      contents: read
      packages: read
    steps:
      - name: Login to ghcr.io
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u "${{ github.actor }}" --password-stdin
      - name: Pull current image
        run: docker pull ${{ env.LOCAL_IMAGE }}
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@0.23.0
        with:
          image-ref: ${{ env.LOCAL_IMAGE }}
          exit-code: "1"
          ignore-unfixed: true
          vuln-type: "os,library"
          severity: "HIGH,CRITICAL"
          skip-dirs: /usr/local/bin/
          scanners: "vuln"
          hide-progress: true

  test-bats:
    name: Run Bats Tests
    runs-on: ubuntu-22.04
    needs:
      - build
    permissions:
      contents: read
      packages: read
    steps:
      - name: Login to ghcr.io
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u "${{ github.actor }}" --password-stdin
      - name: Pull current image
        run: docker pull ${{ env.LOCAL_IMAGE }}
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: true
      - name: Run bats tests
        run: |
          docker run --rm \
            --volume ${PWD}/:/code/ \
            --workdir /code/ \
            --entrypoint "" \
            ${{ env.LOCAL_IMAGE }} \
            ./test/bats/bin/bats ./test/

  publish-tags:
    name: Publish Dist Images
    if: startsWith(github.ref, 'refs/tags/v')
    needs:
      - test-shellcheck
      - test-trivy
      - test-bats
    runs-on: ubuntu-22.04
    permissions:
      contents: read
      packages: write
    steps:
      - name: Export extra envs
        uses: FranzDiebold/github-env-vars-action@v2
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Prepare docker buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to ghcr.io
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u "${{ github.actor }}" --password-stdin
      - name: Build Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          cache-from: type=gha
          cache-to: type=gha,mode=max
          tags: ghcr.io/ironhalik/kubectl-action:${{ env.CI_REF_NAME }},ghcr.io/ironhalik/kubectl-action:${{ env.CI_SHA_SHORT }}
